### ISSUE TITLE
[Contribution] How to run from Luci

### ISSUE THREAD

**Issue by neoOpus** [tavinus/opkg-upgrade#14]
Here is an easier way to run this command without the need to use Putty and SSH.

0- install the shell command according to the tutorial and take not of where it was saved (you can lookup for it using WinSCP)
1- install (luci-app-commands)
2- refresh your browser page (F5)
3- on LUCI top menu find ( System \ Custom Commands
4 - select Configuration tab
5- click add button
6- insert a relevant description (example: opkg-upgrade)
7- on command field insert the path to the script (with the command name and taking care of the extension existence or not) [example: /usr/sbin/opkg-upgrade -f] Note: add -f or --force to make it do the upgrade without the need to add the Custom arguments yourself, optionally you can check the Custom arguments if you want this to be more flexible and allows you to adjust the execution to your actual need.

I hope this help

**Comment by tavinus** [comment]
Good to know it works.  
  
Having said that, not sure I recommend this method.  
Other things could make it go wrong.  
  
Also, I don't think it is easier (maybe if you have some crazy aversion to terminal for some reason).  
  
Tav

**Comment by tavinus** [comment]
This info would be nice on the wiki
